name = "performance-operator"
compatibility_date = "2024-01-01"

[env.production]
name = "performance-operator"

[env.preview]
name = "performance-operator-preview"

# Build configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# Environment variables (add these in Cloudflare dashboard)
# NEXT_PUBLIC_GA_ID = "G-XXXXXXXXXX"
# NEXT_PUBLIC_SITE_URL = "https://performanceoperator.com" 